apiVersion: v1
kind: ConfigMap

metadata:
  name: ai-platform-config
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform
    app.kubernetes.io/part-of: ai-llm-platform

data:
  # API Gateway
  AUTH_SERVICE_URL: "http://auth-service:8001"
  AI_SERVICE_URL: "http://ai-service:8002"
  RAG_SERVICE_URL: "http://rag-service:8003"

  # Auth Service
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"

  # RAG Service
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  EMBEDDING_DIMENSION: "384"
  CHUNK_SIZE: "700"
  CHUNK_OVERLAP: "100"
  TOP_K: "5"

  # AI Service
  LLM_MODEL: "llama3.2:3b"
  LLM_BASE_URL: "http://host.docker.internal:11434/v1"