apiVersion: v1
kind: Secret

metadata:
  name: ai-platform-secret
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform
    app.kubernetes.io/part-of: ai-llm-platform

type: Opaque

stringData:

  # PostgreSQL
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"

  # Auth Service
  JWT_SECRET_KEY: "development-only-change-before-production"

  # AI Service
  LLM_API_KEY: "local-vllm"

  # Database Connections
  AUTH_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/auth_db"
  RAG_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rag_db"