apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: ai-platform
  labels:
    app: auth-service

spec:
  type: ClusterIP

  selector:
    app: auth-service

  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP