apiVersion: v1
kind: Service

metadata:
  name: rag-service
  namespace: ai-platform
  labels:
    app: rag-service

spec:
  type: ClusterIP

  selector:
    app: rag-service

  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP